In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3, 5)
print(x)

tensor([[[-3.0227e+31,  4.5817e-41, -3.0227e+31,  4.5817e-41,  7.8482e-37],
         [ 0.0000e+00,  7.8482e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,         nan,         nan,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  4.5817e-41,  0.0000e+00,  0.0000e+00],
         [ 1.2612e-44,  0.0000e+00, -6.0762e+28,  4.5817e-41,  2.2909e-37],
         [ 0.0000e+00,         nan,         nan,  0.0000e+00,  0.0000e+00]],

        [[        nan,         nan,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 4.5817e-41,  1.0089e-43,  0.0000e+00,  1.5414e-44,  0.0000e+00],
         [-6.0762e+28,  4.5817e-41,  2.2910e-37,  0.0000e+00,  1.4013e-45]],

        [[ 0.0000e+00,  3.9236e-44,  0.0000e+00,         nan,         nan],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.0179e-43],
         [ 0.0000e+00,  1.5414e-44,  0.0000e+00, -6.0762e+28,  4.5817e-41]],

        [[ 2.2910e-37,  0.0000e+00, -6.0365e+28,  4.5817e-41,  4.4842e-44],
    

Construct a randomly initialized matrix:



In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8868, 0.7663, 0.4987],
        [0.6949, 0.7832, 0.7137],
        [0.0466, 0.1038, 0.4239],
        [0.0989, 0.3931, 0.2360],
        [0.8460, 0.6009, 0.7415]])


Construct a matrix filled zeros and of dtype long:



In [11]:
x = torch.zeros(5, 3, dtype=torch.float64)
print(x)
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.float64


Construct a tensor directly from data:



In [13]:
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3609,  0.5322, -1.8103],
        [-0.0163, -0.2376,  0.0280],
        [ 0.0628,  0.3851,  0.1677],
        [ 2.1082, -1.4220, -0.4135],
        [ 0.1868, -1.0079, -0.7977]])


Get its size:



In [15]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6814,  0.5977, -1.2626],
        [ 0.6284,  0.0370,  0.0528],
        [ 0.9234,  1.0405,  0.5791],
        [ 2.6303, -1.0488, -0.2781],
        [ 0.3311, -0.8070, -0.1868]])


Addition: syntax 2



In [17]:
print(torch.add(x, y))

tensor([[ 0.6814,  0.5977, -1.2626],
        [ 0.6284,  0.0370,  0.0528],
        [ 0.9234,  1.0405,  0.5791],
        [ 2.6303, -1.0488, -0.2781],
        [ 0.3311, -0.8070, -0.1868]])


Addition: providing an output tensor as argument



In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6814,  0.5977, -1.2626],
        [ 0.6284,  0.0370,  0.0528],
        [ 0.9234,  1.0405,  0.5791],
        [ 2.6303, -1.0488, -0.2781],
        [ 0.3311, -0.8070, -0.1868]])


Addition: in-place



In [20]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6814,  0.5977, -1.2626],
        [ 0.6284,  0.0370,  0.0528],
        [ 0.9234,  1.0405,  0.5791],
        [ 2.6303, -1.0488, -0.2781],
        [ 0.3311, -0.8070, -0.1868]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!




In [24]:
print(x)
print(x[:, 1])

print(x[3:5,2])


tensor([[ 0.3609,  0.5322, -1.8103],
        [-0.0163, -0.2376,  0.0280],
        [ 0.0628,  0.3851,  0.1677],
        [ 2.1082, -1.4220, -0.4135],
        [ 0.1868, -1.0079, -0.7977]])
tensor([ 0.5322, -0.2376,  0.3851, -1.4220, -1.0079])
tensor([-0.4135, -0.7977])


AttributeError: module 'torch' has no attribute 'view'

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [27]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([ 0.3208, -0.5595,  0.8407, -0.5460,  0.8413,  0.7755, -0.8242,  0.3704,
         0.0294,  0.6212,  1.4838,  0.0981,  0.5737, -0.7189, -1.8453, -0.7508])
tensor([[ 0.3208, -0.5595,  0.8407, -0.5460,  0.8413,  0.7755, -0.8242,  0.3704],
        [ 0.0294,  0.6212,  1.4838,  0.0981,  0.5737, -0.7189, -1.8453, -0.7508]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [28]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6187])
-0.6186621189117432


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [29]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

In [35]:
import numpy as np
a = np.zeros((5,3))
b = np.ones((3,1))
c = np.matmul(a,b)
print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [37]:
import numpy as np
a = np.ones((5))
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!